# Generated by Django 4.1.7 on 2023-02-23 07:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecycleBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_id', models.IntegerField()),
                ('table_id', models.CharField(max_length=100)),
                ('data', models.JSONField()),
                ('deleted_by', models.CharField(max_length=100)),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
