# Generated by Django 4.1.7 on 2023-02-23 07:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('code', models.CharField(max_length=2, unique=True)),
                ('latitude', models.CharField(blank=True, max_length=20, null=True)),
                ('longitude', models.CharField(blank=True, max_length=20, null=True)),
                ('flag', models.FileField(blank=True, null=True, upload_to='media/flags/4x3/')),
            ],
        ),
        migrations.CreateModel(
            name='LogsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api', models.CharField(help_text='API URL', max_length=1024)),
                ('method', models.CharField(db_index=True, max_length=10)),
                ('client_ip_address', models.CharField(max_length=50)),
                ('client_timezone', models.CharField(blank=True, max_length=60, null=True)),
                ('status_code', models.PositiveSmallIntegerField(db_index=True, help_text='Response status code')),
                ('execution_time', models.CharField(blank=True, max_length=60, null=True)),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('response', models.JSONField(null=True)),
                ('client_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loggerapi.country')),
            ],
        ),
    ]
